// This file is autogenerated by AudioManager!
using of2.Audio;
public class ProjectSpecificAudioManagerInstaller : AudioManagerInstaller {
	public override void InstallBindings() {
		base.InstallBindings();
		Container.Bind<IAudioManagerHelper>().To<ProjectSpecificAudioHelper>().AsSingle();
	}
}
